// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_55_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        real_r_address0,
        real_r_ce0,
        real_r_q0,
        real_r_address1,
        real_r_ce1,
        real_r_we1,
        real_r_d1,
        imag_address0,
        imag_ce0,
        imag_q0,
        imag_address1,
        imag_ce1,
        imag_we1,
        imag_d1,
        grp_fu_534_p_din0,
        grp_fu_534_p_din1,
        grp_fu_534_p_dout0,
        grp_fu_534_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] real_r_address0;
output   real_r_ce0;
input  [31:0] real_r_q0;
output  [9:0] real_r_address1;
output   real_r_ce1;
output   real_r_we1;
output  [31:0] real_r_d1;
output  [9:0] imag_address0;
output   imag_ce0;
input  [31:0] imag_q0;
output  [9:0] imag_address1;
output   imag_ce1;
output   imag_we1;
output  [31:0] imag_d1;
output  [31:0] grp_fu_534_p_din0;
output  [14:0] grp_fu_534_p_din1;
input  [31:0] grp_fu_534_p_dout0;
output   grp_fu_534_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln55_fu_111_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] hamming_address0;
wire   [14:0] hamming_q0;
wire    ap_block_pp0_stage0_11001;
reg   [9:0] real_addr_1_reg_184;
reg   [9:0] real_addr_1_reg_184_pp0_iter1_reg;
reg   [9:0] real_addr_1_reg_184_pp0_iter2_reg;
reg   [9:0] real_addr_1_reg_184_pp0_iter3_reg;
reg   [9:0] real_addr_1_reg_184_pp0_iter4_reg;
reg   [9:0] imag_addr_1_reg_190;
reg   [9:0] imag_addr_1_reg_190_pp0_iter1_reg;
reg   [9:0] imag_addr_1_reg_190_pp0_iter2_reg;
reg   [9:0] imag_addr_1_reg_190_pp0_iter3_reg;
reg   [9:0] imag_addr_1_reg_190_pp0_iter4_reg;
reg   [14:0] w_reg_196;
reg  signed [31:0] real_load_reg_201;
reg  signed [31:0] imag_load_reg_206;
wire   [31:0] zext_ln57_fu_135_p1;
reg   [17:0] trunc_ln1_reg_217;
reg   [17:0] trunc_ln2_reg_222;
wire   [63:0] zext_ln55_fu_123_p1;
wire    ap_block_pp0_stage0;
reg   [10:0] i_1_fu_44;
wire   [10:0] add_ln55_fu_117_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i;
reg    hamming_ce0_local;
reg    real_r_ce0_local;
reg    real_r_we1_local;
wire  signed [31:0] sext_ln58_fu_160_p1;
reg    real_r_ce1_local;
reg    imag_ce0_local;
reg    imag_we1_local;
wire  signed [31:0] sext_ln59_fu_164_p1;
reg    imag_ce1_local;
wire   [14:0] grp_fu_99_p1;
wire   [31:0] grp_fu_99_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 i_1_fu_44 = 11'd0;
#0 ap_done_reg = 1'b0;
end

fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_55_3_hamming_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
hamming_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hamming_address0),
    .ce0(hamming_ce0_local),
    .q0(hamming_q0)
);

fft_kernel_mul_32s_15ns_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
mul_32s_15ns_32_3_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(imag_load_reg_206),
    .din1(grp_fu_99_p1),
    .ce(1'b1),
    .dout(grp_fu_99_p2)
);

fft_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln55_fu_111_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_44 <= add_ln55_fu_117_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_44 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        imag_addr_1_reg_190 <= zext_ln55_fu_123_p1;
        imag_addr_1_reg_190_pp0_iter1_reg <= imag_addr_1_reg_190;
        real_addr_1_reg_184 <= zext_ln55_fu_123_p1;
        real_addr_1_reg_184_pp0_iter1_reg <= real_addr_1_reg_184;
        w_reg_196 <= hamming_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        imag_addr_1_reg_190_pp0_iter2_reg <= imag_addr_1_reg_190_pp0_iter1_reg;
        imag_addr_1_reg_190_pp0_iter3_reg <= imag_addr_1_reg_190_pp0_iter2_reg;
        imag_addr_1_reg_190_pp0_iter4_reg <= imag_addr_1_reg_190_pp0_iter3_reg;
        real_addr_1_reg_184_pp0_iter2_reg <= real_addr_1_reg_184_pp0_iter1_reg;
        real_addr_1_reg_184_pp0_iter3_reg <= real_addr_1_reg_184_pp0_iter2_reg;
        real_addr_1_reg_184_pp0_iter4_reg <= real_addr_1_reg_184_pp0_iter3_reg;
        trunc_ln1_reg_217 <= {{grp_fu_534_p_dout0[31:14]}};
        trunc_ln2_reg_222 <= {{grp_fu_99_p2[31:14]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag_load_reg_206 <= imag_q0;
        real_load_reg_201 <= real_r_q0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_111_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 11'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hamming_ce0_local = 1'b1;
    end else begin
        hamming_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag_ce0_local = 1'b1;
    end else begin
        imag_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        imag_ce1_local = 1'b1;
    end else begin
        imag_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        imag_we1_local = 1'b1;
    end else begin
        imag_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_r_ce0_local = 1'b1;
    end else begin
        real_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        real_r_ce1_local = 1'b1;
    end else begin
        real_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        real_r_we1_local = 1'b1;
    end else begin
        real_r_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln55_fu_117_p2 = (ap_sig_allocacmp_i + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_534_p_ce = 1'b1;

assign grp_fu_534_p_din0 = real_load_reg_201;

assign grp_fu_534_p_din1 = zext_ln57_fu_135_p1;

assign grp_fu_99_p1 = zext_ln57_fu_135_p1;

assign hamming_address0 = zext_ln55_fu_123_p1;

assign icmp_ln55_fu_111_p2 = ((ap_sig_allocacmp_i == 11'd1024) ? 1'b1 : 1'b0);

assign imag_address0 = zext_ln55_fu_123_p1;

assign imag_address1 = imag_addr_1_reg_190_pp0_iter4_reg;

assign imag_ce0 = imag_ce0_local;

assign imag_ce1 = imag_ce1_local;

assign imag_d1 = sext_ln59_fu_164_p1;

assign imag_we1 = imag_we1_local;

assign real_r_address0 = zext_ln55_fu_123_p1;

assign real_r_address1 = real_addr_1_reg_184_pp0_iter4_reg;

assign real_r_ce0 = real_r_ce0_local;

assign real_r_ce1 = real_r_ce1_local;

assign real_r_d1 = sext_ln58_fu_160_p1;

assign real_r_we1 = real_r_we1_local;

assign sext_ln58_fu_160_p1 = $signed(trunc_ln1_reg_217);

assign sext_ln59_fu_164_p1 = $signed(trunc_ln2_reg_222);

assign zext_ln55_fu_123_p1 = ap_sig_allocacmp_i;

assign zext_ln57_fu_135_p1 = w_reg_196;

endmodule //fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_55_3
