-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_55_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    real_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    real_r_ce0 : OUT STD_LOGIC;
    real_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    real_r_ce1 : OUT STD_LOGIC;
    real_r_we1 : OUT STD_LOGIC;
    real_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    imag_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    imag_ce0 : OUT STD_LOGIC;
    imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    imag_ce1 : OUT STD_LOGIC;
    imag_we1 : OUT STD_LOGIC;
    imag_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_534_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_534_p_din1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    grp_fu_534_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_534_p_ce : OUT STD_LOGIC );
end;


architecture behav of fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_55_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln55_fu_111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal hamming_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal hamming_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal real_addr_1_reg_184 : STD_LOGIC_VECTOR (9 downto 0);
    signal real_addr_1_reg_184_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal real_addr_1_reg_184_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal real_addr_1_reg_184_pp0_iter3_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal real_addr_1_reg_184_pp0_iter4_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal imag_addr_1_reg_190 : STD_LOGIC_VECTOR (9 downto 0);
    signal imag_addr_1_reg_190_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal imag_addr_1_reg_190_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal imag_addr_1_reg_190_pp0_iter3_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal imag_addr_1_reg_190_pp0_iter4_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal w_reg_196 : STD_LOGIC_VECTOR (14 downto 0);
    signal real_load_reg_201 : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_load_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln57_fu_135_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1_reg_217 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln2_reg_222 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln55_fu_123_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_1_fu_44 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln55_fu_117_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (10 downto 0);
    signal hamming_ce0_local : STD_LOGIC;
    signal real_r_ce0_local : STD_LOGIC;
    signal real_r_we1_local : STD_LOGIC;
    signal sext_ln58_fu_160_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal real_r_ce1_local : STD_LOGIC;
    signal imag_ce0_local : STD_LOGIC;
    signal imag_we1_local : STD_LOGIC;
    signal sext_ln59_fu_164_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_ce1_local : STD_LOGIC;
    signal grp_fu_99_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_99_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_kernel_mul_32s_15ns_32_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_55_3_hamming_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component fft_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    hamming_U : component fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_55_3_hamming_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hamming_address0,
        ce0 => hamming_ce0_local,
        q0 => hamming_q0);

    mul_32s_15ns_32_3_1_U8 : component fft_kernel_mul_32s_15ns_32_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 15,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => imag_load_reg_206,
        din1 => grp_fu_99_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_99_p2);

    flow_control_loop_pipe_sequential_init_U : component fft_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_44_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln55_fu_111_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_1_fu_44 <= add_ln55_fu_117_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_44 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                imag_addr_1_reg_190 <= zext_ln55_fu_123_p1(10 - 1 downto 0);
                imag_addr_1_reg_190_pp0_iter1_reg <= imag_addr_1_reg_190;
                real_addr_1_reg_184 <= zext_ln55_fu_123_p1(10 - 1 downto 0);
                real_addr_1_reg_184_pp0_iter1_reg <= real_addr_1_reg_184;
                w_reg_196 <= hamming_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                imag_addr_1_reg_190_pp0_iter2_reg <= imag_addr_1_reg_190_pp0_iter1_reg;
                imag_addr_1_reg_190_pp0_iter3_reg <= imag_addr_1_reg_190_pp0_iter2_reg;
                imag_addr_1_reg_190_pp0_iter4_reg <= imag_addr_1_reg_190_pp0_iter3_reg;
                real_addr_1_reg_184_pp0_iter2_reg <= real_addr_1_reg_184_pp0_iter1_reg;
                real_addr_1_reg_184_pp0_iter3_reg <= real_addr_1_reg_184_pp0_iter2_reg;
                real_addr_1_reg_184_pp0_iter4_reg <= real_addr_1_reg_184_pp0_iter3_reg;
                trunc_ln1_reg_217 <= grp_fu_534_p_dout0(31 downto 14);
                trunc_ln2_reg_222 <= grp_fu_99_p2(31 downto 14);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                imag_load_reg_206 <= imag_q0;
                real_load_reg_201 <= real_r_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln55_fu_117_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv11_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln55_fu_111_p2)
    begin
        if (((icmp_ln55_fu_111_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_1_fu_44, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_i <= i_1_fu_44;
        end if; 
    end process;

    grp_fu_534_p_ce <= ap_const_logic_1;
    grp_fu_534_p_din0 <= real_load_reg_201;
    grp_fu_534_p_din1 <= zext_ln57_fu_135_p1(15 - 1 downto 0);
    grp_fu_99_p1 <= zext_ln57_fu_135_p1(15 - 1 downto 0);
    hamming_address0 <= zext_ln55_fu_123_p1(10 - 1 downto 0);

    hamming_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hamming_ce0_local <= ap_const_logic_1;
        else 
            hamming_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln55_fu_111_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv11_400) else "0";
    imag_address0 <= zext_ln55_fu_123_p1(10 - 1 downto 0);
    imag_address1 <= imag_addr_1_reg_190_pp0_iter4_reg;
    imag_ce0 <= imag_ce0_local;

    imag_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imag_ce0_local <= ap_const_logic_1;
        else 
            imag_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    imag_ce1 <= imag_ce1_local;

    imag_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            imag_ce1_local <= ap_const_logic_1;
        else 
            imag_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    imag_d1 <= sext_ln59_fu_164_p1;
    imag_we1 <= imag_we1_local;

    imag_we1_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            imag_we1_local <= ap_const_logic_1;
        else 
            imag_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    real_r_address0 <= zext_ln55_fu_123_p1(10 - 1 downto 0);
    real_r_address1 <= real_addr_1_reg_184_pp0_iter4_reg;
    real_r_ce0 <= real_r_ce0_local;

    real_r_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            real_r_ce0_local <= ap_const_logic_1;
        else 
            real_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    real_r_ce1 <= real_r_ce1_local;

    real_r_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            real_r_ce1_local <= ap_const_logic_1;
        else 
            real_r_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    real_r_d1 <= sext_ln58_fu_160_p1;
    real_r_we1 <= real_r_we1_local;

    real_r_we1_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            real_r_we1_local <= ap_const_logic_1;
        else 
            real_r_we1_local <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln58_fu_160_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_217),32));

        sext_ln59_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_reg_222),32));

    zext_ln55_fu_123_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i),64));
    zext_ln57_fu_135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(w_reg_196),32));
end behav;
