-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln75 : IN STD_LOGIC_VECTOR (3 downto 0);
    sub78 : IN STD_LOGIC_VECTOR (8 downto 0);
    zext_ln78 : IN STD_LOGIC_VECTOR (3 downto 0);
    half_stride : IN STD_LOGIC_VECTOR (9 downto 0);
    sub_ln78_cast : IN STD_LOGIC_VECTOR (3 downto 0);
    real_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    real_r_ce0 : OUT STD_LOGIC;
    real_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    imag_ce0 : OUT STD_LOGIC;
    imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_real_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    out_real_ce1 : OUT STD_LOGIC;
    out_real_we1 : OUT STD_LOGIC;
    out_real_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_imag_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    out_imag_ce1 : OUT STD_LOGIC;
    out_imag_we1 : OUT STD_LOGIC;
    out_imag_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_534_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_534_p_din1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_534_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_534_p_ce : OUT STD_LOGIC );
end;


architecture behav of fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln80_reg_411 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal twR_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal twR_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal twI_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal twI_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_222_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_226 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal reg_230 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln78_cast_cast_fu_234_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln78_cast_cast_reg_406 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln80_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_411_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_411_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_411_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pos_fu_272_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal pos_reg_415 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln85_fu_282_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln85_reg_420 : STD_LOGIC_VECTOR (9 downto 0);
    signal top_fu_296_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal top_reg_425 : STD_LOGIC_VECTOR (9 downto 0);
    signal top_reg_425_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal w_real_reg_441 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_imag_reg_446 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln94_fu_316_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln94_reg_451 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln94_reg_451_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln94_reg_451_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln94_reg_451_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal b_real_reg_467 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_imag_reg_473 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln89_fu_322_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln89_reg_479 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln90_fu_326_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln90_reg_484 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln92_fu_330_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln92_reg_489 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln92_reg_489_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal a_real_reg_501 : STD_LOGIC_VECTOR (31 downto 0);
    signal bw_real_reg_512 : STD_LOGIC_VECTOR (17 downto 0);
    signal a_imag_reg_517 : STD_LOGIC_VECTOR (31 downto 0);
    signal bw_imag_reg_523 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln105_fu_375_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln105_reg_528 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln106_fu_389_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln106_reg_533 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln89_fu_306_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal k_fu_66 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal k_2_fu_256_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal twR_ce0_local : STD_LOGIC;
    signal twI_ce0_local : STD_LOGIC;
    signal real_r_ce0_local : STD_LOGIC;
    signal real_r_address0_local : STD_LOGIC_VECTOR (9 downto 0);
    signal imag_ce0_local : STD_LOGIC;
    signal imag_address0_local : STD_LOGIC_VECTOR (9 downto 0);
    signal out_real_we1_local : STD_LOGIC;
    signal out_real_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_fu_369_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_real_ce1_local : STD_LOGIC;
    signal out_real_address1_local : STD_LOGIC_VECTOR (9 downto 0);
    signal out_imag_we1_local : STD_LOGIC;
    signal out_imag_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln104_fu_383_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_imag_ce1_local : STD_LOGIC;
    signal out_imag_address1_local : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_218_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_218_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_222_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_222_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln75_cast_fu_238_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln80_fu_262_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal group_fu_266_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln78_readcast_fu_278_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln83_fu_293_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tw_idx_fu_301_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal bot_fu_312_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln98_fu_334_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln101_fu_353_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln98_fu_350_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln101_fu_380_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter4_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to5 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_kernel_mul_32s_15s_32_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_kernel_mul_32s_16s_32_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7_twR_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7_twI_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component fft_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    twR_U : component fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7_twR_ROM_AUTO_1R
    generic map (
        DataWidth => 16,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => twR_address0,
        ce0 => twR_ce0_local,
        q0 => twR_q0);

    twI_U : component fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7_twI_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => twI_address0,
        ce0 => twI_ce0_local,
        q0 => twI_q0);

    mul_32s_16s_32_3_1_U22 : component fft_kernel_mul_32s_16s_32_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_222_p0,
        din1 => grp_fu_222_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_222_p2);

    flow_control_loop_pipe_sequential_init_U : component fft_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    k_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln80_fu_250_p2 = ap_const_lv1_0))) then 
                    k_fu_66 <= k_2_fu_256_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_66 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_imag_reg_517 <= imag_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_real_reg_501 <= real_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                b_imag_reg_473 <= imag_q0;
                b_real_reg_467 <= real_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bw_imag_reg_523 <= add_ln101_fu_353_p2(31 downto 14);
                icmp_ln80_reg_411 <= icmp_ln80_fu_250_p2;
                icmp_ln80_reg_411_pp0_iter1_reg <= icmp_ln80_reg_411;
                icmp_ln80_reg_411_pp0_iter2_reg <= icmp_ln80_reg_411_pp0_iter1_reg;
                icmp_ln80_reg_411_pp0_iter3_reg <= icmp_ln80_reg_411_pp0_iter2_reg;
                pos_reg_415 <= pos_fu_272_p2;
                sext_ln89_reg_479 <= sext_ln89_fu_322_p1;
                sext_ln90_reg_484 <= sext_ln90_fu_326_p1;
                shl_ln85_reg_420 <= shl_ln85_fu_282_p2;
                sub_ln105_reg_528 <= sub_ln105_fu_375_p2;
                    sub_ln78_cast_cast_reg_406(3 downto 0) <= sub_ln78_cast_cast_fu_234_p1(3 downto 0);
                w_imag_reg_446 <= twI_q0;
                w_real_reg_441 <= twR_q0;
                    zext_ln94_reg_451(9 downto 0) <= zext_ln94_fu_316_p1(9 downto 0);
                    zext_ln94_reg_451_pp0_iter2_reg(9 downto 0) <= zext_ln94_reg_451(9 downto 0);
                    zext_ln94_reg_451_pp0_iter3_reg(9 downto 0) <= zext_ln94_reg_451_pp0_iter2_reg(9 downto 0);
                    zext_ln94_reg_451_pp0_iter4_reg(9 downto 0) <= zext_ln94_reg_451_pp0_iter3_reg(9 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                bw_real_reg_512 <= sub_ln98_fu_334_p2(31 downto 14);
                sub_ln106_reg_533 <= sub_ln106_fu_389_p2;
                top_reg_425 <= top_fu_296_p2;
                top_reg_425_pp0_iter1_reg <= top_reg_425;
                    zext_ln92_reg_489(9 downto 0) <= zext_ln92_fu_330_p1(9 downto 0);
                    zext_ln92_reg_489_pp0_iter3_reg(9 downto 0) <= zext_ln92_reg_489(9 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then
                reg_226 <= grp_fu_222_p2;
                reg_230 <= grp_fu_534_p_dout0;
            end if;
        end if;
    end process;
    sub_ln78_cast_cast_reg_406(9 downto 4) <= "000000";
    zext_ln94_reg_451(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln94_reg_451_pp0_iter2_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln94_reg_451_pp0_iter3_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln94_reg_451_pp0_iter4_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln92_reg_489(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";
    zext_ln92_reg_489_pp0_iter3_reg(63 downto 10) <= "000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter4_stage0, ap_idle_pp0_0to3, ap_idle_pp0_1to5, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to5 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln101_fu_353_p2 <= std_logic_vector(unsigned(reg_226) + unsigned(reg_230));
    add_ln103_fu_369_p2 <= std_logic_vector(unsigned(a_real_reg_501) + unsigned(sext_ln98_fu_350_p1));
    add_ln104_fu_383_p2 <= std_logic_vector(unsigned(a_imag_reg_517) + unsigned(sext_ln101_fu_380_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln80_reg_411)
    begin
        if (((icmp_ln80_reg_411 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, icmp_ln80_reg_411_pp0_iter3_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln80_reg_411_pp0_iter3_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to5 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to5 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, k_fu_66, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_66;
        end if; 
    end process;

    bot_fu_312_p2 <= std_logic_vector(unsigned(top_reg_425) + unsigned(half_stride));
    group_fu_266_p2 <= std_logic_vector(shift_right(unsigned(ap_sig_allocacmp_k_1),to_integer(unsigned('0' & zext_ln75_cast_fu_238_p1(10-1 downto 0)))));

    grp_fu_218_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, b_real_reg_467, b_imag_reg_473, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_218_p0 <= b_real_reg_467;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_218_p0 <= b_imag_reg_473;
            else 
                grp_fu_218_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_218_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_218_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, sext_ln90_fu_326_p1, sext_ln90_reg_484, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_218_p1 <= sext_ln90_reg_484(15 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_218_p1 <= sext_ln90_fu_326_p1(15 - 1 downto 0);
            else 
                grp_fu_218_p1 <= "XXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_218_p1 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_222_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, b_real_reg_467, b_imag_reg_473, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_222_p0 <= b_imag_reg_473;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_222_p0 <= b_real_reg_467;
            else 
                grp_fu_222_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_222_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_222_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, sext_ln89_fu_322_p1, sext_ln89_reg_479, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_222_p1 <= sext_ln89_reg_479(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_222_p1 <= sext_ln89_fu_322_p1(16 - 1 downto 0);
            else 
                grp_fu_222_p1 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_222_p1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_534_p_ce <= ap_const_logic_1;
    grp_fu_534_p_din0 <= grp_fu_218_p0;
    grp_fu_534_p_din1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_218_p1),16));
    icmp_ln80_fu_250_p2 <= "1" when (ap_sig_allocacmp_k_1 = ap_const_lv10_200) else "0";
    imag_address0 <= imag_address0_local;

    imag_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, zext_ln94_fu_316_p1, zext_ln92_reg_489, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            imag_address0_local <= zext_ln92_reg_489(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imag_address0_local <= zext_ln94_fu_316_p1(10 - 1 downto 0);
        else 
            imag_address0_local <= "XXXXXXXXXX";
        end if; 
    end process;

    imag_ce0 <= imag_ce0_local;

    imag_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            imag_ce0_local <= ap_const_logic_1;
        else 
            imag_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    k_2_fu_256_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv10_1));
    out_imag_address1 <= out_imag_address1_local;

    out_imag_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, zext_ln94_reg_451_pp0_iter4_reg, zext_ln92_reg_489_pp0_iter3_reg, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_imag_address1_local <= zext_ln94_reg_451_pp0_iter4_reg(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            out_imag_address1_local <= zext_ln92_reg_489_pp0_iter3_reg(10 - 1 downto 0);
        else 
            out_imag_address1_local <= "XXXXXXXXXX";
        end if; 
    end process;

    out_imag_ce1 <= out_imag_ce1_local;

    out_imag_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            out_imag_ce1_local <= ap_const_logic_1;
        else 
            out_imag_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    out_imag_d1 <= out_imag_d1_local;

    out_imag_d1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, sub_ln106_reg_533, ap_block_pp0_stage1, ap_block_pp0_stage0, add_ln104_fu_383_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_imag_d1_local <= sub_ln106_reg_533;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            out_imag_d1_local <= add_ln104_fu_383_p2;
        else 
            out_imag_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    out_imag_we1 <= out_imag_we1_local;

    out_imag_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            out_imag_we1_local <= ap_const_logic_1;
        else 
            out_imag_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    out_real_address1 <= out_real_address1_local;

    out_real_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, zext_ln94_reg_451_pp0_iter4_reg, zext_ln92_reg_489_pp0_iter3_reg, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                out_real_address1_local <= zext_ln94_reg_451_pp0_iter4_reg(10 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                out_real_address1_local <= zext_ln92_reg_489_pp0_iter3_reg(10 - 1 downto 0);
            else 
                out_real_address1_local <= "XXXXXXXXXX";
            end if;
        else 
            out_real_address1_local <= "XXXXXXXXXX";
        end if; 
    end process;

    out_real_ce1 <= out_real_ce1_local;

    out_real_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            out_real_ce1_local <= ap_const_logic_1;
        else 
            out_real_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    out_real_d1 <= out_real_d1_local;

    out_real_d1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, sub_ln105_reg_528, ap_block_pp0_stage1, ap_block_pp0_stage0, add_ln103_fu_369_p2)
    begin
        if ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                out_real_d1_local <= sub_ln105_reg_528;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                out_real_d1_local <= add_ln103_fu_369_p2;
            else 
                out_real_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            out_real_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    out_real_we1 <= out_real_we1_local;

    out_real_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            out_real_we1_local <= ap_const_logic_1;
        else 
            out_real_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pos_fu_272_p2 <= (trunc_ln80_fu_262_p1 and sub78);
    real_r_address0 <= real_r_address0_local;

    real_r_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, zext_ln94_fu_316_p1, zext_ln92_fu_330_p1, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            real_r_address0_local <= zext_ln92_fu_330_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            real_r_address0_local <= zext_ln94_fu_316_p1(10 - 1 downto 0);
        else 
            real_r_address0_local <= "XXXXXXXXXX";
        end if; 
    end process;

    real_r_ce0 <= real_r_ce0_local;

    real_r_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            real_r_ce0_local <= ap_const_logic_1;
        else 
            real_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln101_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bw_imag_reg_523),32));

        sext_ln89_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_real_reg_441),32));

        sext_ln90_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_imag_reg_446),32));

        sext_ln98_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bw_real_reg_512),32));

    shl_ln85_fu_282_p2 <= std_logic_vector(shift_left(unsigned(group_fu_266_p2),to_integer(unsigned('0' & zext_ln78_readcast_fu_278_p1(10-1 downto 0)))));
    sub_ln105_fu_375_p2 <= std_logic_vector(unsigned(a_real_reg_501) - unsigned(sext_ln98_fu_350_p1));
    sub_ln106_fu_389_p2 <= std_logic_vector(unsigned(a_imag_reg_517) - unsigned(sext_ln101_fu_380_p1));
    sub_ln78_cast_cast_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln78_cast),10));
    sub_ln98_fu_334_p2 <= std_logic_vector(unsigned(reg_226) - unsigned(reg_230));
    top_fu_296_p2 <= std_logic_vector(unsigned(shl_ln85_reg_420) + unsigned(zext_ln83_fu_293_p1));
    trunc_ln80_fu_262_p1 <= ap_sig_allocacmp_k_1(9 - 1 downto 0);
    twI_address0 <= zext_ln89_fu_306_p1(9 - 1 downto 0);

    twI_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            twI_ce0_local <= ap_const_logic_1;
        else 
            twI_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    twR_address0 <= zext_ln89_fu_306_p1(9 - 1 downto 0);

    twR_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            twR_ce0_local <= ap_const_logic_1;
        else 
            twR_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tw_idx_fu_301_p2 <= std_logic_vector(shift_left(unsigned(zext_ln83_fu_293_p1),to_integer(unsigned('0' & sub_ln78_cast_cast_reg_406(10-1 downto 0)))));
    zext_ln75_cast_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln75),10));
    zext_ln78_readcast_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln78),10));
    zext_ln83_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pos_reg_415),10));
    zext_ln89_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tw_idx_fu_301_p2),64));
    zext_ln92_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(top_reg_425_pp0_iter1_reg),64));
    zext_ln94_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bot_fu_312_p2),64));
end behav;
