#!/usr/bin/env python3
import vitis
import os
import time
import shutil
import glob
from datetime import datetime

# Create names
tmpdir = 'tmp'
date = datetime.now().strftime("%Y%m%d%I%M%S")
workspace_name = 'workspace_'+date
workspace = os.path.join(tmpdir, workspace_name)
comp_name = "hls_component"
cwd = os.getcwd()

# Delete the workspace if already exists
if (os.path.isdir(tmpdir)):
    shutil.rmtree(tmpdir, ignore_errors=True)
    print(f"Deleted workspaces in {tmpdir}")

# Print names
print(f"CWD is {cwd}")
print(f"Workspace path is {workspace}")
print(f"Creating component {comp_name}")

# Create a client object
client = vitis.create_client()

# Set Workspace
client.set_workspace(workspace)

# Create HLS Component
comp = client.create_hls_component(name=comp_name)

# Get config file object
cfg_path = os.path.join(workspace, comp_name, 'hls_config.cfg')
cfg_obj = client.get_config_file(cfg_path)

# Set part
cfg_obj.set_value('',key = 'part', value='xcvu47p-fsvh2892-2-e')

# libraries
xcl2_dir = os.path.expanduser("~/aws-fpga/vitis/examples/vitis_examples/common/includes/xcl2")
xcl2_cpp = os.path.join(xcl2_dir, "xcl2.cpp")
xrt_path = "/opt/xilinx/xrt/include"

# Add kernel sources, test bench files, set top
cfg_obj.add_lines('hls',['syn.file='+cwd+'/../src/vadd.cpp'])
cfg_obj.add_lines('hls',['tb.file='+cwd+'/../src/host.cpp'])
cfg_obj.add_lines('hls',['tb.file='+xcl2_cpp])
cfg_obj.set_value('hls', key='tb.cflags', value=f'-I{xcl2_dir} -I{xrt_path}')

# Set options
cfg_obj.set_value('hls',key='syn.top', value='vadd')
cfg_obj.set_value('hls',key='clock', value='3ns')
cfg_obj.set_value('hls',key='flow_target', value='vivado') #
cfg_obj.set_value('hls',key='package.output.format', value='rtl') #
cfg_obj.set_value('hls',key='package.output.syn', value='false') #

# Execute the desired steps:
comp.run('SYNTHESIS')

# concatenate outputs
verilog_dir = os.path.join(workspace, comp_name, comp_name, 'hls', 'syn', 'verilog')
output_file = os.path.join(cwd, 'design', 'concat_top.v') # Saves to your current working directory

print(f"Concatenating Verilog files into {output_file}...")

# find all .v files generated by HLS
v_files = glob.glob(os.path.join(verilog_dir, '*.*v'))

# append top module last
top_module = os.path.join(verilog_dir, 'vadd.v')
if top_module in v_files:
    v_files.remove(top_module)
    v_files.append(top_module)

# Write them all into one file with comments separating them
with open(output_file, 'w') as outfile:
    for v_file in v_files:
        with open(v_file, 'r') as infile:
            outfile.write(infile.read())
            outfile.write("\n\n")

print("Concatenation complete!")

# Clean up, delete the workspace
if (os.path.isdir(tmpdir)):
#     shutil.rmtree(tmpdir, ignore_errors=True)
    print(f"Deleted workspaces in {tmpdir}")

# Close the client connection and terminate the vitis server
vitis.dispose()