// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln75,
        sub78,
        zext_ln78,
        half_stride,
        sub_ln78_cast,
        real_r_address0,
        real_r_ce0,
        real_r_q0,
        imag_address0,
        imag_ce0,
        imag_q0,
        out_real_address1,
        out_real_ce1,
        out_real_we1,
        out_real_d1,
        out_imag_address1,
        out_imag_ce1,
        out_imag_we1,
        out_imag_d1,
        grp_fu_534_p_din0,
        grp_fu_534_p_din1,
        grp_fu_534_p_dout0,
        grp_fu_534_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] zext_ln75;
input  [8:0] sub78;
input  [3:0] zext_ln78;
input  [9:0] half_stride;
input  [3:0] sub_ln78_cast;
output  [9:0] real_r_address0;
output   real_r_ce0;
input  [31:0] real_r_q0;
output  [9:0] imag_address0;
output   imag_ce0;
input  [31:0] imag_q0;
output  [9:0] out_real_address1;
output   out_real_ce1;
output   out_real_we1;
output  [31:0] out_real_d1;
output  [9:0] out_imag_address1;
output   out_imag_ce1;
output   out_imag_we1;
output  [31:0] out_imag_d1;
output  [31:0] grp_fu_534_p_din0;
output  [15:0] grp_fu_534_p_din1;
input  [31:0] grp_fu_534_p_dout0;
output   grp_fu_534_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln80_reg_411;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [8:0] twR_address0;
wire   [15:0] twR_q0;
wire   [8:0] twI_address0;
wire   [14:0] twI_q0;
wire   [31:0] grp_fu_222_p2;
reg   [31:0] reg_226;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] reg_230;
wire   [9:0] sub_ln78_cast_cast_fu_234_p1;
reg   [9:0] sub_ln78_cast_cast_reg_406;
wire   [0:0] icmp_ln80_fu_250_p2;
reg   [0:0] icmp_ln80_reg_411_pp0_iter1_reg;
reg   [0:0] icmp_ln80_reg_411_pp0_iter2_reg;
reg   [0:0] icmp_ln80_reg_411_pp0_iter3_reg;
wire   [8:0] pos_fu_272_p2;
reg   [8:0] pos_reg_415;
wire   [9:0] shl_ln85_fu_282_p2;
reg   [9:0] shl_ln85_reg_420;
wire   [9:0] top_fu_296_p2;
reg   [9:0] top_reg_425;
reg   [9:0] top_reg_425_pp0_iter1_reg;
reg   [15:0] w_real_reg_441;
reg   [14:0] w_imag_reg_446;
wire   [63:0] zext_ln94_fu_316_p1;
reg   [63:0] zext_ln94_reg_451;
reg   [63:0] zext_ln94_reg_451_pp0_iter2_reg;
reg   [63:0] zext_ln94_reg_451_pp0_iter3_reg;
reg   [63:0] zext_ln94_reg_451_pp0_iter4_reg;
reg  signed [31:0] b_real_reg_467;
reg  signed [31:0] b_imag_reg_473;
wire  signed [31:0] sext_ln89_fu_322_p1;
reg  signed [31:0] sext_ln89_reg_479;
wire  signed [31:0] sext_ln90_fu_326_p1;
reg  signed [31:0] sext_ln90_reg_484;
wire   [63:0] zext_ln92_fu_330_p1;
reg   [63:0] zext_ln92_reg_489;
reg   [63:0] zext_ln92_reg_489_pp0_iter3_reg;
reg   [31:0] a_real_reg_501;
reg   [17:0] bw_real_reg_512;
reg   [31:0] a_imag_reg_517;
reg   [17:0] bw_imag_reg_523;
wire   [31:0] sub_ln105_fu_375_p2;
reg   [31:0] sub_ln105_reg_528;
wire   [31:0] sub_ln106_fu_389_p2;
reg   [31:0] sub_ln106_reg_533;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln89_fu_306_p1;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage0;
reg   [9:0] k_fu_66;
wire   [9:0] k_2_fu_256_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_k_1;
reg    twR_ce0_local;
reg    twI_ce0_local;
reg    real_r_ce0_local;
reg   [9:0] real_r_address0_local;
reg    imag_ce0_local;
reg   [9:0] imag_address0_local;
reg    out_real_we1_local;
reg   [31:0] out_real_d1_local;
wire   [31:0] add_ln103_fu_369_p2;
reg    out_real_ce1_local;
reg   [9:0] out_real_address1_local;
reg    out_imag_we1_local;
reg   [31:0] out_imag_d1_local;
wire   [31:0] add_ln104_fu_383_p2;
reg    out_imag_ce1_local;
reg   [9:0] out_imag_address1_local;
reg  signed [31:0] grp_fu_218_p0;
reg  signed [14:0] grp_fu_218_p1;
reg  signed [31:0] grp_fu_222_p0;
reg  signed [15:0] grp_fu_222_p1;
wire   [9:0] zext_ln75_cast_fu_238_p1;
wire   [8:0] trunc_ln80_fu_262_p1;
wire   [9:0] group_fu_266_p2;
wire   [9:0] zext_ln78_readcast_fu_278_p1;
wire   [9:0] zext_ln83_fu_293_p1;
wire   [9:0] tw_idx_fu_301_p2;
wire   [9:0] bot_fu_312_p2;
wire   [31:0] sub_ln98_fu_334_p2;
wire   [31:0] add_ln101_fu_353_p2;
wire  signed [31:0] sext_ln98_fu_350_p1;
wire  signed [31:0] sext_ln101_fu_380_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage0;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to5;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 k_fu_66 = 10'd0;
#0 ap_done_reg = 1'b0;
end

fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7_twR_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
twR_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twR_address0),
    .ce0(twR_ce0_local),
    .q0(twR_q0)
);

fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7_twI_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
twI_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twI_address0),
    .ce0(twI_ce0_local),
    .q0(twI_q0)
);

fft_kernel_mul_32s_16s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_32s_16s_32_3_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_222_p0),
    .din1(grp_fu_222_p1),
    .ce(1'b1),
    .dout(grp_fu_222_p2)
);

fft_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln80_fu_250_p2 == 1'd0))) begin
            k_fu_66 <= k_2_fu_256_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_66 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_imag_reg_517 <= imag_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_real_reg_501 <= real_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_imag_reg_473 <= imag_q0;
        b_real_reg_467 <= real_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bw_imag_reg_523 <= {{add_ln101_fu_353_p2[31:14]}};
        icmp_ln80_reg_411 <= icmp_ln80_fu_250_p2;
        icmp_ln80_reg_411_pp0_iter1_reg <= icmp_ln80_reg_411;
        icmp_ln80_reg_411_pp0_iter2_reg <= icmp_ln80_reg_411_pp0_iter1_reg;
        icmp_ln80_reg_411_pp0_iter3_reg <= icmp_ln80_reg_411_pp0_iter2_reg;
        pos_reg_415 <= pos_fu_272_p2;
        sext_ln89_reg_479 <= sext_ln89_fu_322_p1;
        sext_ln90_reg_484 <= sext_ln90_fu_326_p1;
        shl_ln85_reg_420 <= shl_ln85_fu_282_p2;
        sub_ln105_reg_528 <= sub_ln105_fu_375_p2;
        sub_ln78_cast_cast_reg_406[3 : 0] <= sub_ln78_cast_cast_fu_234_p1[3 : 0];
        w_imag_reg_446 <= twI_q0;
        w_real_reg_441 <= twR_q0;
        zext_ln94_reg_451[9 : 0] <= zext_ln94_fu_316_p1[9 : 0];
        zext_ln94_reg_451_pp0_iter2_reg[9 : 0] <= zext_ln94_reg_451[9 : 0];
        zext_ln94_reg_451_pp0_iter3_reg[9 : 0] <= zext_ln94_reg_451_pp0_iter2_reg[9 : 0];
        zext_ln94_reg_451_pp0_iter4_reg[9 : 0] <= zext_ln94_reg_451_pp0_iter3_reg[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bw_real_reg_512 <= {{sub_ln98_fu_334_p2[31:14]}};
        sub_ln106_reg_533 <= sub_ln106_fu_389_p2;
        top_reg_425 <= top_fu_296_p2;
        top_reg_425_pp0_iter1_reg <= top_reg_425;
        zext_ln92_reg_489[9 : 0] <= zext_ln92_fu_330_p1[9 : 0];
        zext_ln92_reg_489_pp0_iter3_reg[9 : 0] <= zext_ln92_reg_489[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_226 <= grp_fu_222_p2;
        reg_230 <= grp_fu_534_p_dout0;
    end
end

always @ (*) begin
    if (((icmp_ln80_reg_411 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln80_reg_411_pp0_iter3_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_k_1 = k_fu_66;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_218_p0 = b_real_reg_467;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_218_p0 = b_imag_reg_473;
        end else begin
            grp_fu_218_p0 = 'bx;
        end
    end else begin
        grp_fu_218_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_218_p1 = sext_ln90_reg_484;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_218_p1 = sext_ln90_fu_326_p1;
        end else begin
            grp_fu_218_p1 = 'bx;
        end
    end else begin
        grp_fu_218_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_222_p0 = b_imag_reg_473;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_222_p0 = b_real_reg_467;
        end else begin
            grp_fu_222_p0 = 'bx;
        end
    end else begin
        grp_fu_222_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_222_p1 = sext_ln89_reg_479;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_222_p1 = sext_ln89_fu_322_p1;
        end else begin
            grp_fu_222_p1 = 'bx;
        end
    end else begin
        grp_fu_222_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        imag_address0_local = zext_ln92_reg_489;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag_address0_local = zext_ln94_fu_316_p1;
    end else begin
        imag_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        imag_ce0_local = 1'b1;
    end else begin
        imag_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_imag_address1_local = zext_ln94_reg_451_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_imag_address1_local = zext_ln92_reg_489_pp0_iter3_reg;
    end else begin
        out_imag_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_imag_ce1_local = 1'b1;
    end else begin
        out_imag_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_imag_d1_local = sub_ln106_reg_533;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_imag_d1_local = add_ln104_fu_383_p2;
    end else begin
        out_imag_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_imag_we1_local = 1'b1;
    end else begin
        out_imag_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_real_address1_local = zext_ln94_reg_451_pp0_iter4_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_real_address1_local = zext_ln92_reg_489_pp0_iter3_reg;
        end else begin
            out_real_address1_local = 'bx;
        end
    end else begin
        out_real_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_real_ce1_local = 1'b1;
    end else begin
        out_real_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_real_d1_local = sub_ln105_reg_528;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_real_d1_local = add_ln103_fu_369_p2;
        end else begin
            out_real_d1_local = 'bx;
        end
    end else begin
        out_real_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_real_we1_local = 1'b1;
    end else begin
        out_real_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        real_r_address0_local = zext_ln92_fu_330_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_r_address0_local = zext_ln94_fu_316_p1;
    end else begin
        real_r_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        real_r_ce0_local = 1'b1;
    end else begin
        real_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        twI_ce0_local = 1'b1;
    end else begin
        twI_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        twR_ce0_local = 1'b1;
    end else begin
        twR_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln101_fu_353_p2 = (reg_226 + reg_230);

assign add_ln103_fu_369_p2 = ($signed(a_real_reg_501) + $signed(sext_ln98_fu_350_p1));

assign add_ln104_fu_383_p2 = ($signed(a_imag_reg_517) + $signed(sext_ln101_fu_380_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign bot_fu_312_p2 = (top_reg_425 + half_stride);

assign group_fu_266_p2 = ap_sig_allocacmp_k_1 >> zext_ln75_cast_fu_238_p1;

assign grp_fu_534_p_ce = 1'b1;

assign grp_fu_534_p_din0 = grp_fu_218_p0;

assign grp_fu_534_p_din1 = grp_fu_218_p1;

assign icmp_ln80_fu_250_p2 = ((ap_sig_allocacmp_k_1 == 10'd512) ? 1'b1 : 1'b0);

assign imag_address0 = imag_address0_local;

assign imag_ce0 = imag_ce0_local;

assign k_2_fu_256_p2 = (ap_sig_allocacmp_k_1 + 10'd1);

assign out_imag_address1 = out_imag_address1_local;

assign out_imag_ce1 = out_imag_ce1_local;

assign out_imag_d1 = out_imag_d1_local;

assign out_imag_we1 = out_imag_we1_local;

assign out_real_address1 = out_real_address1_local;

assign out_real_ce1 = out_real_ce1_local;

assign out_real_d1 = out_real_d1_local;

assign out_real_we1 = out_real_we1_local;

assign pos_fu_272_p2 = (trunc_ln80_fu_262_p1 & sub78);

assign real_r_address0 = real_r_address0_local;

assign real_r_ce0 = real_r_ce0_local;

assign sext_ln101_fu_380_p1 = $signed(bw_imag_reg_523);

assign sext_ln89_fu_322_p1 = $signed(w_real_reg_441);

assign sext_ln90_fu_326_p1 = $signed(w_imag_reg_446);

assign sext_ln98_fu_350_p1 = $signed(bw_real_reg_512);

assign shl_ln85_fu_282_p2 = group_fu_266_p2 << zext_ln78_readcast_fu_278_p1;

assign sub_ln105_fu_375_p2 = ($signed(a_real_reg_501) - $signed(sext_ln98_fu_350_p1));

assign sub_ln106_fu_389_p2 = ($signed(a_imag_reg_517) - $signed(sext_ln101_fu_380_p1));

assign sub_ln78_cast_cast_fu_234_p1 = sub_ln78_cast;

assign sub_ln98_fu_334_p2 = (reg_226 - reg_230);

assign top_fu_296_p2 = (shl_ln85_reg_420 + zext_ln83_fu_293_p1);

assign trunc_ln80_fu_262_p1 = ap_sig_allocacmp_k_1[8:0];

assign twI_address0 = zext_ln89_fu_306_p1;

assign twR_address0 = zext_ln89_fu_306_p1;

assign tw_idx_fu_301_p2 = zext_ln83_fu_293_p1 << sub_ln78_cast_cast_reg_406;

assign zext_ln75_cast_fu_238_p1 = zext_ln75;

assign zext_ln78_readcast_fu_278_p1 = zext_ln78;

assign zext_ln83_fu_293_p1 = pos_reg_415;

assign zext_ln89_fu_306_p1 = tw_idx_fu_301_p2;

assign zext_ln92_fu_330_p1 = top_reg_425_pp0_iter1_reg;

assign zext_ln94_fu_316_p1 = bot_fu_312_p2;

always @ (posedge ap_clk) begin
    sub_ln78_cast_cast_reg_406[9:4] <= 6'b000000;
    zext_ln94_reg_451[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln94_reg_451_pp0_iter2_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln94_reg_451_pp0_iter3_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln94_reg_451_pp0_iter4_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln92_reg_489[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln92_reg_489_pp0_iter3_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
end

endmodule //fft_kernel_fft_kernel_Pipeline_VITIS_LOOP_80_7
