---- FFT Inference Test ----
Loading input frames into DDR...
Configuring FFT kernel registers...
Starting FFT kernel...
Waiting for completion...
Compute cycles: ...
Transfer cycles: ...
---- TEST PASSED ----